import fs from "fs";
import path from "path";

const distDir = path.resolve("dist");
const distClientDir = path.resolve("dist/client");
const outputPublicDir = path.resolve(".output/public");

// 1. If TanStack Start output to dist/client, promote dist/client contents to dist/ root
if (fs.existsSync(distClientDir)) {
  fs.cpSync(distClientDir, distDir, { recursive: true });
  fs.rmSync(distClientDir, { recursive: true, force: true });
  if (fs.existsSync(path.resolve("dist/server"))) {
    fs.rmSync(path.resolve("dist/server"), { recursive: true, force: true });
  }
  console.log("✓ Promoted dist/client assets to root dist/ directory.");
} else if (fs.existsSync(outputPublicDir)) {
  // 2. Otherwise copy from .output/public
  fs.cpSync(outputPublicDir, distDir, { recursive: true });
  console.log("✓ Copied build output from .output/public to dist/");
}

// 3. Ensure index.html exists in dist/ and create 404.html for GitHub Pages fallback
const indexHtmlPath = path.join(distDir, "index.html");
const fallbackHtmlPath = path.join(distDir, "404.html");

if (fs.existsSync(indexHtmlPath)) {
  fs.copyFileSync(indexHtmlPath, fallbackHtmlPath);
  console.log("✓ Created dist/404.html for GitHub Pages SPA fallback.");
} else {
  // If index.html wasn't generated by Vite, build fallback index.html linking client assets
  const assetsDir = path.join(distDir, "assets");
  if (fs.existsSync(assetsDir)) {
    const files = fs.readdirSync(assetsDir);
    const cssFile = files.find((f) => f.endsWith(".css"));
    const jsFile = files.find((f) => f.startsWith("index-") && f.endsWith(".js"));

    const cssTag = cssFile ? `<link rel="stylesheet" href="/portfolio/assets/${cssFile}">` : "";
    const jsTag = jsFile ? `<script type="module" src="/portfolio/assets/${jsFile}"></script>` : "";

    const htmlContent = `<!DOCTYPE html>
<html lang="en" class="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Chaman Lal — UI/UX Designer & Responsive Front-End Developer</title>
    <meta name="description" content="Portfolio of Chaman Lal, Sr. UI/UX Designer and Front-End Developer with 8+ years of continuous product experience." />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Sora:wght@300;400;600;700&family=Manrope:wght@300;400;500;600&family=JetBrains+Mono:wght@400;500&display=swap" />
    <link rel="icon" href="/portfolio/favicon.ico" type="image/x-icon" />
    ${cssTag}
  </head>
  <body class="dark bg-ink text-foreground">
    <div id="root"></div>
    ${jsTag}
  </body>
</html>`;

    fs.writeFileSync(indexHtmlPath, htmlContent, "utf-8");
    fs.writeFileSync(fallbackHtmlPath, htmlContent, "utf-8");
    console.log("✓ Generated dist/index.html and dist/404.html from assets.");
  }
}
